from selenium import webdriver
from selenium.webdriver.common.by import By
import time

chrome_driver = r'C:\Users\12500\Desktop\Capstone\capstone_24_schenker\capstone\seleniumTest\chromedriver_win32\chromedriver.exe'
browser = webdriver.Chrome(executable_path=chrome_driver)
browser.get('http://127.0.0.1:8000/login/')
browser.maximize_window()
userName = browser.find_element(By.NAME, "username")
password = browser.find_element(By.NAME, "password")
login = browser.find_element(By.NAME, 'login')
# userName.value = 'cap'
userName.send_keys('cap')
time.sleep(1)
password.send_keys('stone')
time.sleep(1)
login.click()
time.sleep(1)
li_1 = browser.find_element(By.XPATH, "//li[@data-username='homepage']") 
li_1.click()
time.sleep(1)
li_2 = browser.find_element(By.XPATH, "//li[@data-username='create new job']") 
li_2.click()
time.sleep(1)
li_3 = browser.find_element(By.XPATH, "//li[@data-username='all jobs']") 
li_3.click()
time.sleep(1)
li_4 = browser.find_element(By.XPATH, "//li[@data-username='all applicants']") 
li_4.click()
time.sleep(1)
li_1 = browser.find_element(By.XPATH, "//li[@data-username='homepage']") 
li_1.click()
time.sleep(1)
openJobs = browser.find_element(By.XPATH, "//a[@href='alljobs']")
openJobs.click()
time.sleep(1)
li_1 = browser.find_element(By.XPATH, "//li[@data-username='homepage']") 
li_1.click()
time.sleep(1)
pendingApplicants = browser.find_element(By.XPATH, "//a[@href='allapplicants']")
pendingApplicants.click()
time.sleep(1)
li_3 = browser.find_element(By.XPATH, "//li[@data-username='all jobs']") 
li_3.click()
time.sleep(1)
jobTitle1 = browser.find_element(By.XPATH, "//a[@href='/job/1/']")
jobTitle1.click()
time.sleep(1)
li_3 = browser.find_element(By.XPATH, "//li[@data-username='all jobs']") 
li_3.click()
time.sleep(1)
jobTitle2 = browser.find_element(By.XPATH, "//a[@href='/job/1/']")
jobTitle2.click()
time.sleep(1)
li_4 = browser.find_element(By.XPATH, "//li[@data-username='all applicants']") 
li_4.click()
time.sleep(1)
applicant1 = browser.find_element(By.XPATH, "//a[@href='/applicant/1']")
applicant1.click()
time.sleep(1)
li_4 = browser.find_element(By.XPATH, "//li[@data-username='all applicants']") 
li_4.click()
time.sleep(1)
applicant2 = browser.find_element(By.XPATH, "//a[@href='/applicant/2']")
applicant2.click()
time.sleep(2)
logout = browser.find_element(By.XPATH, "//li[@data-username='Disabled Menu']")
logout.click()


# navBar = browser.find_element(By.CLASS_NAME, "pcoded-navbar")
# navBar.click()