# Generated by Django 3.2.13 on 2022-07-19 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('applicant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_resume', models.FileField(upload_to='applicant_resume')),
                ('recruiter_decision', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Reprofiled', 'Reprofiled')], max_length=20)),
                ('reprofile', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HiringManagerModel',
            fields=[
                ('hiring_manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hiring_manager_name', models.CharField(max_length=50)),
                ('hiring_manager_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedJobModel',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50, unique=True)),
                ('job_keywords', models.CharField(max_length=200)),
                ('job_matching_date', models.DateField(auto_now_add=True)),
                ('job_update_date', models.DateField(auto_now=True)),
                ('job_description', models.FileField(upload_to='job_description')),
                ('job_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20)),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPredictionModel',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant_skills', models.CharField(max_length=100)),
                ('applicant_percent', models.FloatField(max_length=50)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicantmodel')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.matchedjobmodel')),
            ],
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='home.matchedjobmodel'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='job_id_reprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reprofile', to='home.matchedjobmodel'),
        ),
        migrations.CreateModel(
            name='ApplicantHistoryModel',
            fields=[
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recruiter_decision', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Reprofiled', 'Reprofiled')], max_length=20)),
                ('status_change_date', models.DateTimeField(auto_now_add=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicantmodel')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.matchedjobmodel')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
