# Generated by Django 3.2.13 on 2022-07-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiringManagerModel',
        ),
    ]
