# Generated by Django 4.0.4 on 2022-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='applicant_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hiringmanagermodel',
            name='hiring_manager_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchedjobmodel',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchedjobmodel',
            name='recruiter_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionresultmodel',
            name='applicant_rank',
            field=models.IntegerField(),
        ),
    ]
