# Generated by Django 4.0.4 on 2022-05-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_loginmodel_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('applicant_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_resume', models.FileField(upload_to='applicant_resume')),
                ('recruiter_decision', models.CharField(choices=[('P', 'Pending'), ('S', 'Shortlisted'), ('R', 'Rejected')], max_length=1)),
                ('applicant_experience', models.CharField(max_length=100)),
                ('applicant_education', models.CharField(max_length=100)),
                ('applicant_skills', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HiringManagerModel',
            fields=[
                ('hiring_manager_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('hiring_manager_name', models.CharField(max_length=50)),
                ('hiring_manager_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResultModel',
            fields=[
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.applicantmodel')),
                ('applicant_percent', models.FloatField(max_length=50)),
                ('applicant_rank', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedJobModel',
            fields=[
                ('job_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('job_department', models.CharField(max_length=100)),
                ('job_matching_date', models.DateField(auto_now_add=True)),
                ('job_update_date', models.DateField(auto_now=True)),
                ('recruiter_id', models.IntegerField(max_length=50)),
                ('hiring_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hiringmanagermodel')),
            ],
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchedjobmodel'),
        ),
    ]
