# Generated by Django 4.0.4 on 2022-05-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_applicantmodel_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresultmodel',
            name='applicant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.applicantmodel'),
        ),
    ]
