# Generated by Django 4.0.4 on 2022-05-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_matchedjobmodel_recruiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedjobmodel',
            name='job_description',
            field=models.FileField(default='job1.pdf', upload_to='job_description'),
            preserve_default=False,
        ),
    ]
