# Generated by Django 4.0.4 on 2022-05-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_matchedjobmodel_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresultmodel',
            name='applicant_rank',
        ),
    ]
