# Generated by Django 4.0.4 on 2022-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_predictionresultmodel_applicant_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='applicant_percent',
            field=models.FloatField(default=0.5, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PredictionResultModel',
        ),
    ]
