# Generated by Django 4.0.4 on 2022-06-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_applicantmodel_applicant_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedjobmodel',
            name='job_department',
        ),
    ]
