# Generated by Django 4.0.4 on 2022-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_matchedjobmodel_job_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedjobmodel',
            name='job_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
