# Generated by Django 4.0.4 on 2022-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_matchedjobmodel_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedjobmodel',
            name='job_keywords',
            field=models.CharField(default='job keywords', max_length=200),
            preserve_default=False,
        ),
    ]
