# Generated by Django 4.0.4 on 2022-06-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_matchedjobmodel_job_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmodel',
            name='applicant_percent',
        ),
        migrations.CreateModel(
            name='ModelPredictionModel',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant_percent', models.FloatField(max_length=50)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicantmodel')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchedjobmodel')),
            ],
        ),
    ]
