# Generated by Django 4.0.4 on 2022-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_applicantmodel_applicant_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmodel',
            name='applicant_education',
        ),
        migrations.RemoveField(
            model_name='applicantmodel',
            name='applicant_experience',
        ),
        migrations.RemoveField(
            model_name='applicantmodel',
            name='applicant_skills',
        ),
        migrations.AddField(
            model_name='modelpredictionmodel',
            name='applicant_education',
            field=models.CharField(default='bachelor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpredictionmodel',
            name='applicant_experience',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelpredictionmodel',
            name='applicant_skills',
            field=models.CharField(default='html', max_length=100),
            preserve_default=False,
        ),
    ]
