# Generated by Django 4.0.4 on 2022-06-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_applicantmodel_applicant_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='core.matchedjobmodel'),
        ),
    ]
