# Generated by Django 4.0.4 on 2022-06-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_applicantmodel_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='reprofile',
            field=models.BooleanField(default=False),
        ),
    ]
