# Generated by Django 4.0.4 on 2022-06-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_applicantmodel_reprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmodel',
            name='job_id_reprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reprofile', to='core.matchedjobmodel'),
        ),
    ]
