# Generated by Django 4.0.4 on 2022-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_applicantmodel_job_id_reprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='recruiter_decision',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
