# Generated by Django 4.0.4 on 2022-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_applicantmodel_recruiter_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='recruiter_decision',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Reprofiled', 'Reprofiled')], max_length=20),
        ),
    ]
