# Generated by Django 4.0.4 on 2022-06-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_applicantmodel_recruiter_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpredictionmodel',
            name='applicant_education',
        ),
        migrations.RemoveField(
            model_name='modelpredictionmodel',
            name='applicant_experience',
        ),
    ]
