# Generated by Django 4.0.4 on 2022-06-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_remove_modelpredictionmodel_applicant_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantHistoryModel',
            fields=[
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recruiter_decision', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Reprofiled', 'Reprofiled')], max_length=20)),
                ('status_change_date', models.DateField(auto_now_add=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicantmodel')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matchedjobmodel')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
