# Generated by Django 4.0.4 on 2022-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_applicanthistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanthistorymodel',
            name='status_change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
