# Generated by Django 4.0.4 on 2022-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_applicanthistorymodel_status_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedjobmodel',
            name='hiring_manager_id',
        ),
        migrations.AddField(
            model_name='matchedjobmodel',
            name='job_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
            preserve_default=False,
        ),
    ]
